# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0e0e368
_src_path: gh:blakeNaccarato/copier-python
github_repo_name: gradedoc
include_funding: true
override: false
override_coveragerc: false
override_env: false
override_flake8: false
override_gitattributes: false
override_pyrightconfig: false
override_pytest: false
override_vscode_extensions: false
override_vscode_launch: false
override_vscode_settings: false
override_vscode_tasks: false
project_email: blake.naccarato+gradedoc@gmail.com
project_name: gradedoc
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: '3.10'
year_of_project_creation: 2022
